import ad from "./assets/cast.png";
import gel from "./assets/gel.jpg";
import keratin from "./assets/keratin.jpg"
import neem from "./assets/neem.jpg"
import rose from './assets/rose.png'

const productsData = [
  {
    id: 1,
    name: "Organic Hair Fall Protection Oil",
    size: "120ml",
    price: 1500,
    image: ad,
    inStock: true,
    type: "Hair Care",
    isPopular: true,
  },
  {
    id: 2,
    name: "Herbal Hair Fall Protection Shampoo",
    size: "260ml",
    price: 850,
    inStock: true,
    image: rose,
    type: "Hair Care",
  },
  {
    id: 3,
    name: "Organic Keratin Enriched Hair Oil",
    size: "120ml",
    price: 1500,
    image: neem,
    inStock: false,
    type: "Deals",
  },
  {
    id: 4,
    name: "Moisturizing Hair Mask",
    size: "200g",
    price: 1200,
    inStock: true,
    image: keratin,
    type: "Hair Care",
  },
  {
    id: 5,
    name: "Volumizing Shampoo",
    size: "300ml",
    price: 900,
    inStock: true,
    type: "Hair Care",
    image: gel,
  },
  {
    id: 6,
    name: "Argan Oil Hair Serum",
    size: "100ml",
    price: 1800,
    inStock: false,
    type: "Deals",
    image: ad,
  },
  {
    id: 7,
    name: "Coconut Oil Hair Treatment",
    size: "150ml",
    price: 600,
    inStock: true,
    image: ad,
    type: "Hair Care",
  },
  {
    id: 8,
    name: "Anti-Dandruff Shampoo",
    size: "250ml",
    price: 750,
    inStock: true,
    image: ad,
    type: "Hair Care",
  },
  {
    id: 9,
    name: "Color Protection Conditioner",
    size: "200ml",
    price: 950,
    inStock: false,
    image: ad,
    type: "Deals",
  },
  {
    id: 10,
    name: "Scalp Detox Serum",
    size: "80ml",
    price: 2000,
    inStock: true,
    image: ad,
    type: "Hair Care",
  },
  {
    id: 11,
    name: "Hydrating Hair Mist",
    size: "150ml",
    price: 1100,
    inStock: true,
    image: ad,
    type: "Hair Care",
  },
  {
    id: 12,
    name: "Repairing Hair Mask",
    size: "180g",
    price: 1300,
    inStock: false,
    image: ad,
    type: "Deals",
  },
  {
    id: 13,
    name: "Smoothing Hair Oil",
    size: "100ml",
    price: 1400,
    inStock: true,
    image: ad,
    type: "Hair Care",
  },
  {
    id: 14,
    name: "Herbal Hair Tonic",
    size: "200ml",
    price: 800,
    inStock: true,
    image: ad,
    type: "Hair Care",
  },
  {
    id: 15,
    name: "Deep Conditioning Treatment",
    size: "220g",
    price: 1600,
    inStock: false,
    image: ad,
    type: "Deals",
  },
];

export default productsData;